In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as skl
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/train.csv")
df.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [ ]:
df.isna().sum()

id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [ ]:
df.dtypes

id                    int64
age                   int64
gender               object
course               object
study_hours         float64
class_attendance    float64
internet_access      object
sleep_hours         float64
sleep_quality        object
study_method         object
facility_rating      object
exam_difficulty      object
exam_score          float64
dtype: object

In [ ]:
df.nunique()

id                  630000
age                      8
gender                   3
course                   7
study_hours            792
class_attendance       617
internet_access          2
sleep_hours             66
sleep_quality            3
study_method             5
facility_rating          3
exam_difficulty          3
exam_score             805
dtype: int64

In [ ]:
df.describe()

,id,age,study_hours,class_attendance,sleep_hours,exam_score
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,20.545821,4.002337,71.987261,7.072758,62.506672
std,181865.479132,2.260238,2.359880,17.430098,1.744811,18.916884
min,0.000000,17.000000,0.080000,40.600000,4.100000,19.599000
25%,157499.750000,19.000000,1.970000,57.000000,5.600000,48.800000
50%,314999.500000,21.000000,4.000000,72.600000,7.100000,62.600000
75%,472499.250000,23.000000,6.050000,87.200000,8.600000,76.300000
max,629999.000000,24.000000,7.910000,99.400000,9.900000,100.000000

In [ ]:
df.drop("id",axis=1, inplace=True)

In [ ]:
print(df['sleep_quality'].unique())
print(df['facility_rating'].unique())
print(df['exam_difficulty'].unique())
print(df['gender'].unique())
print(df['internet_access'].unique())
print(df['study_method'].unique())
print(df['course'].unique())

['average' 'poor' 'good']
['low' 'medium' 'high']
['easy' 'moderate' 'hard']
['female' 'other' 'male']
['no' 'yes']
['online videos' 'self-study' 'coaching' 'group study' 'mixed']
['b.sc' 'diploma' 'bca' 'b.com' 'ba' 'bba' 'b.tech']

In [ ]:
# Correct maps matching EXACT unique values
sleep_map = {'poor': 0, 'average': 1, 'good': 2}
rating_map = {'low': 0, 'medium': 1, 'high': 2}
difficulty_map = {'easy': 0, 'moderate': 1, 'hard': 2}

df['sleep_quality'] = df['sleep_quality'].map(sleep_map)
df['facility_rating'] = df['facility_rating'].map(rating_map)
df['exam_difficulty'] = df['exam_difficulty'].map(difficulty_map)
df['internet_access']= df['internet_access'].map({'yes': 1, 'no':0})

# Verify - should show 0, 1, 2 only (no NaN)
print(df['sleep_quality'].unique())
print(df['facility_rating'].unique())
print(df['exam_difficulty'].unique())
print(df['internet_access'].unique())

[1 0 2]
[0 1 2]
[0 1 2]
[0 1]

In [ ]:
df

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,21,female,b.sc,7.91,98.8,0,4.9,1,online videos,0,0,78.300
1,18,other,diploma,4.95,94.8,1,4.7,0,self-study,1,1,46.700
2,20,female,b.sc,4.68,92.6,1,5.8,0,coaching,2,1,99.000
3,19,male,b.sc,2.00,49.5,1,8.3,1,group study,2,1,63.900
4,23,male,bca,7.65,86.9,1,9.6,2,self-study,2,0,100.000
...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,female,b.tech,4.86,70.7,1,4.1,2,mixed,2,1,69.500
629996,21,female,ba,7.08,54.4,1,4.5,1,mixed,0,1,78.900
629997,24,male,bca,0.64,44.2,1,4.3,0,online videos,0,1,19.599
629998,20,male,b.com,1.54,75.1,1,8.2,1,group study,2,1,59.100
629999,18,other,b.tech,3.94,75.3,1,5.8,0,online videos,0,0,37.200

In [ ]:
df=pd.get_dummies(df,columns=['gender','study_method', 'course'], drop_first=True)
df

,age,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,gender_male,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,course_b.sc,course_b.tech,course_ba,course_bba,course_bca,course_diploma
0,21,7.91,98.8,0,4.9,1,0,0,78.300,False,...,False,False,True,False,True,False,False,False,False,False
1,18,4.95,94.8,1,4.7,0,1,1,46.700,False,...,False,False,False,True,False,False,False,False,False,True
2,20,4.68,92.6,1,5.8,0,2,1,99.000,False,...,False,False,False,False,True,False,False,False,False,False
3,19,2.00,49.5,1,8.3,1,2,1,63.900,True,...,True,False,False,False,True,False,False,False,False,False
4,23,7.65,86.9,1,9.6,2,2,0,100.000,True,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,4.86,70.7,1,4.1,2,2,1,69.500,False,...,False,True,False,False,False,True,False,False,False,False
629996,21,7.08,54.4,1,4.5,1,0,1,78.900,False,...,False,True,False,False,False,False,True,False,False,False
629997,24,0.64,44.2,1,4.3,0,0,1,19.599,True,...,False,False,True,False,False,False,False,False,True,False
629998,20,1.54,75.1,1,8.2,1,2,1,59.100,True,...,True,False,False,False,False,False,False,False,False,False
629999,18,3.94,75.3,1,5.8,0,0,0,37.200,False,...,False,False,True,False,False,True,False,False,False,False

In [ ]:
print(df.columns.tolist())
print(df.shape)

['age', 'study_hours', 'class_attendance', 'internet_access', 'sleep_hours', 'sleep_quality', 'facility_rating', 'exam_difficulty', 'exam_score', 'gender_male', 'gender_other', 'study_method_group study', 'study_method_mixed', 'study_method_online videos', 'study_method_self-study', 'course_b.sc', 'course_b.tech', 'course_ba', 'course_bba', 'course_bca', 'course_diploma']
(630000, 21)

In [ ]:
df=df.astype({col: int for col in df.select_dtypes(bool).columns})

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df.drop('exam_score', axis=1)
y = df['exam_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error
print("R² Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R² Score: 0.7779290925346727
RMSE: 8.887006615544927

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=500,      # more trees
    max_depth=20,          # prevent overfitting
    min_samples_split=5,  # smoother decisions
    n_jobs=-1,             # use all CPU cores → faster
    random_state=42)
rf.fit(X_train, y_train)
y_pred_rf= rf.predict(X_test)
print("R² Score:", r2_score(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

R² Score: 0.7689055691660248
RMSE: 9.065764005555101

In [ ]:
from xgboost import XGBRegressor
xg=XGBRegressor(n_estimators=500, learning_rate=0.05, n_jobs=-1, max_depth=6,subsample=0.8, colsample_bytree=0.8)
xg.fit(X_train,y_train)
y_pred_xg= xg.predict(X_test)
print("R2 score", r2_score(y_test,y_pred_xg))
print("RMSE ",np.sqrt(mean_squared_error(y_test,y_pred_xg)))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3858398344.py, line 2)